import { createClient } from "@supabase/supabase-js";
import { projectId, publicAnonKey } from "../../../utils/supabase/info";

// Supabase client singleton — uses the project credentials already present in the repo.
// No VITE_ env vars are needed: the values come from utils/supabase/info.tsx which is
// auto-generated by Figma Make and kept in sync with the connected project.
export const supabase = createClient(
  `https://${projectId}.supabase.co`,
  publicAnonKey,
);
